version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: petclinic
      MYSQL_USER: springpython
      MYSQL_PASSWORD: springpython
